version: '3.7'
services:
    postgres:
      image: postgres:14.2-alpine
      ports:
        - '5432:5432'
      networks:
        - app
      environment:
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=password
        - POSTGRES_DB=palette_system
      volumes:
        - ./postgres:/var/lib/postgresql/data
        - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    nodejs:
      image: node:20.9-alpine
      ports:
        - 3000:3000
      restart: always
      networks:
        - app
      depends_on:
        - postgres
      volumes:
        - ./:/opt/server
      working_dir: /opt/server
      command: >
       sh -c "npm i --legacy-peer-deps && npm run migrate && npm run start"

networks:
  app:
    driver: local
